# Generated by Django 5.0.2 on 2024-02-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0002_rename_advertiser_ad_advertiser_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
    ]
