# Generated by Django 5.0.2 on 2024-02-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0003_rename_advertiser_id_ad_advertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_ip', models.IntegerField()),
                ('click_time', models.DateTimeField(auto_now=True)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mangement_advertiser.ad')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_ip', models.IntegerField()),
                ('click_time', models.DateTimeField(auto_now=True)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mangement_advertiser.ad')),
            ],
        ),
    ]
