# Generated by Django 5.0.2 on 2024-02-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0004_remove_ad_clicks_remove_ad_views_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='Views',
        ),
    ]
