# Generated by Django 5.0.2 on 2024-02-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0005_rename_view_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='Click',
        ),
        migrations.RenameModel(
            old_name='Clicks',
            new_name='View',
        ),
    ]
