# Generated by Django 5.0.2 on 2024-02-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0007_ad_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
