# Generated by Django 5.0.2 on 2024-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0008_alter_click_user_ip_alter_view_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='click_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='click_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
