# Generated by Django 5.0.2 on 2024-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0009_alter_click_click_time_alter_view_click_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='click_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='click_time',
            field=models.DateTimeField(),
        ),
    ]
