# Generated by Django 5.0.2 on 2024-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangement_advertiser', '0012_saver'),
    ]

    operations = [
        migrations.AddField(
            model_name='saver',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
